### ISSUE TITLE
Can't make the project, no idea what I'm doing

### ISSUE THREAD

**Issue by jkerman2000** [deviant-syndrome/blender-udmf-toolkit#2]
I'm using git bash to run the bootstrap.sh file, but it keeps giving me errors like "zip: command not found." It doesn't seem to recognize rsync as a command either. What am I doing wrong?

**Comment by deviant-syndrome** [comment]
@jkerman2000  Hello! Seems like I've been too confident about the what might be included in the default unix-like OS distributions. 
If `zip` and `rsync` are not available by default, you can install them using your package manager. 
I'll update the readme to include this requirements.
Thank you for trying out this strange project. Cheers!

**Comment by deviant-syndrome** [comment]
@jkerman2000 , also, I did a brief research on Git Bash, since I've never used this environment. It tells me that there is no dedicated package manager for it out of the box. It was recommended to use package managers for Windows, like Scoop or Chocolately, or full-blown MSYS2 / Cygwin environments that have build-in package management. 
Hope this helps. Thank you

**Comment by jkerman2000** [comment]
> @jkerman2000 , also, I did a brief research on Git Bash, since I've never used this environment. It tells me that there is no dedicated package manager for it out of the box. It was recommended to use package managers for Windows, like Scoop or Chocolately, or full-blown MSYS2 / Cygwin environments that have build-in package management. Hope this helps. Thank you

How do I use Chocolately to build the repo?

**Comment by jkerman2000** [comment]
NVM, I used Choco to install zip and rsync and I was able to run the bootstrap file with git without any errors.

**Comment by jkerman2000** [comment]
New problem, I tried to install the resulting zip into Blender 4.0, and when I tried activating it, it gives me this error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\blender-udmf-toolkit-main\__init__.py", line 1, in <module>
    from .operators import export_udmf
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\blender-udmf-toolkit-main\operators\__init__.py", line 1, in <module>
    from .import_udmf import register
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\blender-udmf-toolkit-main\operators\import_udmf.py", line 3, in <module>
    from ..libs import load_udmf_map
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\blender-udmf-toolkit-main\libs\__init__.py", line 1, in <module>
    from .udmfio_bundled import load_udmf_map, write_udmf_map
ImportError: cannot import name 'load_udmf_map' from 'blender-udmf-toolkit-main.libs.udmfio_bundled' (unknown location)

**Comment by deviant-syndrome** [comment]
@jkerman2000 , please hang on, I still haven't managed to give this issue a detailed look. I suspect, that script does zip packaging incorrectly or something. Since I only tested this during development by having a symlink to my local repo from Blender extensions. I will get back to this as soon as I can. Thank you.
